#!/usr/bin/env python3
"""Compile a release-decision report for the autonomous integration branch.

Compares the integration branch against the release branch and summarizes what
the loop has accumulated, so a human (optionally with an AI assistant) can
decide whether to cut a release. This script never mutates the repository, and
never bumps versions, tags, or publishes anything.
"""
from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


def _git(*args: str) -> str:
    try:
        return subprocess.check_output(["git", *args], text=True, stderr=subprocess.STDOUT).strip()
    except Exception as exc:  # noqa: BLE001
        return "(git " + " ".join(args) + " failed: " + str(exc) + ")"


def build_report(base: str, head: str) -> str:
    ahead = _git("rev-list", "--count", base + ".." + head)
    behind = _git("rev-list", "--count", head + ".." + base)
    log = _git("log", "--no-merges", "--pretty=format:- %h %s (%an, %ad)", "--date=short",
               base + ".." + head)
    stat = _git("diff", "--stat", base + "..." + head)
    lines = [
        "# Autonomous integration review: `" + head + "` vs `" + base + "`",
        "",
        "- Commits ahead of `" + base + "`: **" + ahead + "**",
        "- Commits behind `" + base + "`: **" + behind + "**",
        "",
        "## Commits accumulated by the loop",
        "",
        log or "_No unique commits._",
        "",
        "## Changed files",
        "",
        "```",
        stat or "(no differences)",
        "```",
        "",
        "## Release decision checklist (human-gated)",
        "",
        "- [ ] Quality Gate is green on the integration branch",
        "- [ ] Every change is inside product scope (no release/version/updater files)",
        "- [ ] Each change is backed by a test or reproducible evidence",
        "- [ ] Manual smoke of the built app is acceptable",
        "- [ ] Decision: promote to the release branch, or keep iterating",
        "",
        "_Generated by autonomous_release_review. This tooling never bumps versions,",
        "creates tags, or publishes releases - promotion stays a manual human action._",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default="main")
    parser.add_argument("--head", default="autonomous/lab")
    parser.add_argument("--out", type=Path, default=Path("release-review.md"))
    args = parser.parse_args(argv)
    report = build_report(args.base, args.head)
    args.out.write_text(report + "\n", encoding="utf-8")
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
